### ISSUE TITLE
GetDropAndCreateDdl - nullable columns

### ISSUE THREAD

**Issue by DeveloperPotr** [varigence/BimlPit#105]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead go to https://varigence.com/Forums?forumName=BimlStudio or email support@varigence.com
[ ] Other... Please describe:
</code></pre>

## Current behavior

Generates a SQL statement to create a table, but cannot specify if columns are nullable

## Expected behavior
An option or parameter to config is columns are allowed to be NULL or not.

## What is the motivation / use case for changing the behavior?
Not all of the columns are NOT NULL, some columns are allowed to be NULL. The statement generated create a table with all the columns to be NOT NULL.

## Environment

<pre><code>
BimlStudio version: X.Y.Z

Target SSIS Version:

- [ ] 2005
- [ ] 2008
- [ ] 2008 R2
- [ ] 2012
- [ ] 2014
- [x] 2016
- [ ] 2017

Others:

</code></pre>

**Comment by billinkc** [comment]
I am getting NULL/NOT NULL for my generated DDL

Varigence BimlExpress 5.0 (32-bit)
Build 5.0.63501.0
Features and Bundles: No features or bundles have been authorized
Plugins: No plugins have been loaded

Using the following table definition

```
<Biml xmlns="http://schemas.varigence.com/biml.xsd">
    <Connections>
        <Connection Name="Source" ConnectionString="X=y;" />
    </Connections>
    <Databases>
        <Database Name="SourceDb" ConnectionName="Source"/>
    </Databases>
    <Schemas>
        <Schema Name="dbo" DatabaseName="SourceDb" />
    </Schemas>
    <Tables>
        <Table Name="BimlPit105" SchemaName="SourceDb.dbo">
            <Columns>
                <Column Name="IAmNullable" IsNullable="true" />
                <Column Name="NotNullable" IsNullable="false" />
            </Columns>
        </Table>
    </Tables>    
</Biml>
```
I interact with it via
```
<Biml xmlns="http://schemas.varigence.com/biml.xsd">
<#
var t = this.RootNode.Tables[0].GetDropAndCreateDdl();
System.IO.File.WriteAllText(@"C:\tmp\bimlpit105.txt", t.ToString());
#>    
</Biml>
```
The resulting file looks like

```
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-------------------------------------------------------------------
IF EXISTS (SELECT * from sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BimlPit105]') AND type IN (N'U'))
DROP TABLE [dbo].[BimlPit105]
GO

CREATE TABLE [dbo].[BimlPit105]
(
-- Columns Definition
	[IAmNullable] int 
,	[NotNullable] int NOT NULL 

-- Constraints

)
ON "default"
WITH (DATA_COMPRESSION = NONE)
GO

-------------------------------------------------------------------





```

**Comment by jalley3** [comment]
Thanks bill, great example!

**Comment by DeveloperPotr** [comment]
Thanks! You are right Bill. I was looking at the wrong location....

Problem solved!
