### ISSUE TITLE
Importer Issue: script files missing in biml code for scriptcomponentprojects 

### ISSUE THREAD

**Issue by jalley64** [varigence/BimlPit#114]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead go to https://varigence.com/Forums?forumName=BimlStudio or email support@varigence.com
[ ] Other... Please describe:
</code></pre>

## Current behavior

When importing a script component project from an SSIS package, the generated biml is missing the script files in the scriptcomponentproject node. 

## Expected behavior

The script files should aslo be imported

## Minimal reproduction of the problem with instructions
[Package2 - Copy.txt](https://github.com/varigence/BimlPit/files/3302910/Package2.-.Copy.txt)
## Environment

<pre><code>
BimlStudio version: X.Y.Z

Target SSIS Version:

- [ ] 2005
- [ ] 2008
- [ ] 2008 R2
- [ ] 2012
- [ ] 2014
- [ ] 2016
- [ ] 2017

Others:

</code></pre>

**Comment by Sir-nk** [comment]
delete the shit bro its not worht it LMAOm, shit sus:thinkin:🤔🤔🤔

**Comment by DocGitHub** [comment]
Any news ?

**Comment by jalley3** [comment]
This was fixed some time ago
