### ISSUE TITLE
White spacing in Tier declarations causes tier to have null value

### ISSUE THREAD

**Issue by jalley64** [varigence/BimlPit#144]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead go to https://varigence.com/Forums?forumName=Biml or email support@varigence.com
[ ] Other... Please describe:
</code></pre>

## Current behavior

When writing a tier declaration, if there is any whitespace between the start of the word tier to the end of the tier number, then the file's tier gets assigned a null value.  The package still compiles with no warning or error. Users should be able to compile with or without the whitespace shown in the example below.

## Minimal reproduction of the problem with instructions

`template tier = "1"`

## Environment

<pre><code>
BimlExpress version: 5.0.64108

Visual Studio Version:

- [ ] 2005
- [ ] 2008
- [ ] 2010
- [ ] 2012
- [ ] 2013
- [ ] 2015
- [ x] 2017

Target SSIS Version:

- [ ] 2005
- [ ] 2008
- [ ] 2008 R2
- [ ] 2012
- [ ] 2014
- [ ] 2016
- [x ] 2017

Others:

</code></pre>

**Comment by chojrak11** [comment]
XML does not allow whitespaces around " = " so @template directives do not have to, as well. But proper intellisense and error during compilation would be useful.

**Comment by jalley3** [comment]
This is true for XML but the directive statements are actually not XML. We have fixed this issue to allow users to include whitespaces in the tier declaration and it will be included in the next release.
