### ISSUE TITLE
Attribute VersionGuid not showing in Intellisense with BimlExpress

### ISSUE THREAD

**Issue by Frysdisken** [varigence/BimlPit#55]
Shown in BimlStudio Build 5.0.62912.0
![image](https://user-images.githubusercontent.com/19734145/40542887-542f022c-6022-11e8-90ed-219e698e8e5d.png)

Not shown in BimlExpress Build 5.0.62912.0 Visual Studio 2015
![image](https://user-images.githubusercontent.com/19734145/40542987-b90bada8-6022-11e8-97fd-2c21534cc21f.png)

**Comment by jalley3** [comment]
Fixed as of R2
