### ISSUE TITLE
BimlExpress 2018 ConvertPackagesToBiml Raises Error in VS 2017

### ISSUE THREAD

**Issue by aleonard763** [varigence/BimlPit#60]
When I click "Convert Packages to Biml" from the Visual Studio 2017 BimlExpress menu or right-click, I get a dialog box:
---------------------------
Microsoft Visual Studio
---------------------------
BimlExpress

Error importing packages.
---------------------------
OK   
---------------------------

**Comment by jalley3** [comment]
@aleonard763  while we fixed this issue for 2017 some time ago, we also just fixed the issue for 2013 (and other older versions), do you have that reader's information by chance? That way we can invite them to the preview and fix their issue
