### ISSUE TITLE
TFS has extremely slow performance 

### ISSUE THREAD

**Issue by jalley3** [varigence/BimlPit#72]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[x ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead go to https://varigence.com/Forums?forumName=BimlStudio or email support@varigence.com
[ ] Other... Please describe:
</code></pre>

## Current behavior

Sometimes it can take 2-3 minutes to commit work, and sometimes biml studio hangs when adding a new file.

## Expected behavior

Faster performance with better user experience

## Minimal reproduction of the problem with instructions

Use TFS with BimlStudio, and either commit work, view history, or add files to the project.

## What is the motivation / use case for changing the behavior?

Smoother experience

## Environment

<pre><code>
BimlStudio version: X.Y.Z

BimlStudio 2018

Target SSIS Version:

- [ ] 2005
- [ ] 2008
- [ ] 2008 R2
- [ ] 2012
- [ ] 2014
- [ ] 2016
- [ ] 2017

Others:

</code></pre>

**Comment by fluxium** [comment]
Our team is struggling with this right now as well. We are continuing to use the VSTS/TFS experience in Visual Studio to do all our source control until the performance has improved.

**Comment by GrahamEckel** [comment]
We are encountering this too. We are doing a large scale dump and load data migration for an ERP implementation. 

An execute task to create 221 objects without TFS takes <5 seconds in BimlStudio. The same execute task in a different BimlStudio project with TSF integration takes ~30 minutes and opens an average of 40 TFS.exe and Console Window Hosts tasks. 

Currently, I am unable to push these 221 objects to TFS. BimlStudio has been attempting to commit for ~1 hour. 

BimlExpress in VisStudio builds in 30 seconds and commits in 20. 

![bimlstudio with tfs](https://user-images.githubusercontent.com/9220457/44878611-4a26ad80-ac75-11e8-95b0-b477da004bd2.png)

![bimlstudio without tfs](https://user-images.githubusercontent.com/9220457/44878600-44c96300-ac75-11e8-843e-eee1d22a7e2b.PNG)

**Comment by jalley3** [comment]
@fluxium @GrahamEckel The latest iteration of BimlStudio should have significant improvements to both commit and add.

**Comment by GrahamEckel** [comment]
@jalley3 I'm working with Build 5.0.63025.0. Is there a later version? If there is, is it auto updated - can't seem to find a way to update to latest version

**Comment by jalley3** [comment]
Yea, assuming that your support is still active, you should be able to just download it from:

[](https://varigence.com/BimlStudio)

**Comment by GrahamEckel** [comment]
Incredible improvement. Build went from ~1.5hrs to ~7min. Checked in ~250 objects in <30 seconds. See screenshots. 

I would consider this usable for our purposes, but that being said, build in Visual studio using BimlExpress is still <1min.  

Overall, great job. Thanks for sticking with me @jalley3. 

![biml build](https://user-images.githubusercontent.com/9220457/46025396-d2527400-c0b6-11e8-94f9-62b0c48cc9d7.jpg)
![bimlstudio check-in](https://user-images.githubusercontent.com/9220457/46025401-d41c3780-c0b6-11e8-944a-57a4dcc21751.JPG)
