### ISSUE TITLE
Code Editor is not rendering properly in Visual Studio

### ISSUE THREAD

**Issue by jalley3** [varigence/BimlPit#74]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead go to https://varigence.com/Forums?forumName=Biml or email support@varigence.com
[ ] Other... Please describe:
</code></pre>

## Current behavior

The code editor does not properly render in Visual Studio (neither 2012 or 2017).  There is no intellisense, no preview panel, and it reads the include statements as errors (see attached image)

## Expected behavior

Load properly with intellisense, preview panel, etc

## What is the motivation / use case for changing the behavior?

To take advantage of the functionality of BimlExpress

## Environment

<pre><code>
BimlExpress version: 5.0.63025

Visual Studio Version:

- [ ] 2005
- [ ] 2008
- [ ] 2010
- [ x] 2012
- [ ] 2013
- [ ] 2015
- [x ] 2017

Target SSIS Version:

- [ ] 2005
- [ ] 2008
- [ ] 2008 R2
- [ ] 2012
- [ ] 2014
- [ ] 2016
- [ ] 2017

Others:

</code></pre>
![](https://varigence.zendesk.com/attachments/token/1191Yb7VImiqJHXJ8AFcIni3O/?name=image001.png)

![](https://varigence.zendesk.com/attachments/token/kbMcH8B8kiROBsx4b3OuBxhjK/?name=image002.png)

**Comment by scottcurrie** [comment]
This is to the Biml code editor not initializing correctly. The code editor with all of the errors is acutally the default Visual Studio code editor for XML. This usually points to an installation issue. Reinstalling the VSIX may resolve it. If not, anyone encountering this issue should contact support@varigence.com to obtain an instrumented build of BimlExpress that logs additional diagnostic information that we can use to pinpoint where and why the Biml code editor initialization is failing.

Two such initialization failures were resolved for the BimlExpress 2018 R2 release, so also be sure that you are using the latest version.
