### ISSUE TITLE
Package Importer: OleDBSource comes in as TheobaldXtractSapSource

### ISSUE THREAD

**Issue by Frysdisken** [varigence/BimlPit#76]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead go to https://varigence.com/Forums?forumName=Biml or email support@varigence.com
[ ] Other... Please describe:
</code></pre>

## Current behavior

Using Convert SSIS packages to Biml it produces a TheobaldXtractSapSource element.

## Expected behavior

It should come in as a OleDbSource element.

## Minimal reproduction of the problem with instructions

Right click any of the packages in the shared solution and convert any of the SSIS packages to Biml.

## Environment

<pre><code>
BimlExpress version: Build 5.0.63025.0

Visual Studio Version:

- [ ] 2005
- [ ] 2008
- [ ] 2010
- [ ] 2012
- [ ] 2013
- [ ] 2015
- [X] 2017

Target SSIS Version:

- [ ] 2005
- [ ] 2008
- [ ] 2008 R2
- [X] 2012
- [ ] 2014
- [ ] 2016
- [ ] 2017

Others:

</code></pre>
![image](https://user-images.githubusercontent.com/19734145/44345697-51d79c80-a494-11e8-9924-66fb7883a061.png)

**Comment by jalley3** [comment]
It says to click attached but I do not see any attached files. I was not able to recreate this myself, creating a simple package with a dataflow with an oledbsource/dest. It imported as expected. Could you please upload the offending package(s)

**Comment by Frysdisken** [comment]
I've sent it over through the official channel.

**Comment by jalley3** [comment]
This is now fixed, sorry for the inconvenience and thank you for bringing it to our attention.
