### ISSUE TITLE
RetainSameConnection not being tracked in OleDbConnections

### ISSUE THREAD

**Issue by jalley3** [varigence/BimlPit#96]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead go to https://varigence.com/Forums?forumName=Biml or email support@varigence.com
[ ] Other... Please describe:
</code></pre>

## Current behavior

When specifying the RetainSameConnectionProperty as true, it still emits as false in the generated dtsx. 

## Minimal reproduction of the problem with instructions

```
<Biml xmlns="http://schemas.varigence.com/biml.xsd">
<Connections>
  <OleDbConnection Name="UDM" RetainSameConnection="true" ConnectionString="Data Source=Server1;Initial Catalog=Catalog;Provider=SQLNCLI11.1;Integrated Security=SSPI;"></OleDbConnection>
</Connections>
<Packages>
  <Package Name="Test" ConstraintMode="Linear" ProtectionLevel="DontSaveSensitive">
    <Connections>
      <Connection ConnectionName="UDM"></Connection>
    </Connections>
  </Package>
</Packages>        
</Biml>
```

## Environment

<pre><code>
BimlExpress version: 5.0.63501.0

Visual Studio Version:

- [ ] 2005
- [ ] 2008
- [ ] 2010
- [ ] 2012
- [ ] 2013
- [ ] 2015
- [x ] 2017

Target SSIS Version:

- [ ] 2005
- [ ] 2008
- [ ] 2008 R2
- [] 2012
- [ ] 2014
- [ ] 2016
- [x ] 2017 (verified in 2017)

Others:

</code></pre>

**Comment by DocGitHub** [comment]
Any updates on this ?

**Comment by jalley3** [comment]
The fix for this issue is in place and it will be included in the next release. Thank you for your patience. 

In the meantime there is a workaround you can use: 

<Package Name="Test" ConstraintMode="Linear" ProtectionLevel="DontSaveSensitive">
    <Connections>
      <Connection ConnectionName="UDM" RetainSameConnection="True"></Connection>
    </Connections>
  </Package>

If you set the property on the connection reference, like above, it will persist in the generated dtsx file.
